### ISSUE TITLE
Random Number

### ISSUE THREAD

**Issue by dickymr** [arifinoid/project-javascript-functions#1]
https://github.com/arifinoid/project-javascript-functions/blob/1e6635845bf6cdab251b4537d529f9ec0e97895c/index.js#L4

```javascript
 const calculate = Math.floor(Math.random() * 100); 
```
The code above will give result 0-100.
But if u want result 1-100. Try code below.

```javascript
 const calculate = Math.floor(Math.random() * 100) + 1; 
```

- Math.floor() result an integer number
- *100 mean max number from random number
- +1 for doesn't result number 0

My suggest: show percentage of match probability 

and consultation with Roy Kiyoshi for more accurate results.

**Comment by arifinoid** [comment]
Thanks for the tips and advice mate. The last one is part I like the most btw lol @dickymr 😆
